version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: uploading_mast
      MYSQL_ROOT_PASSWORD: Mysql123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - web_network

  app:
    container_name: uploading-mast
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /home/abhi/ABHI/uploading-mast:/app
    networks:
      - web_network
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - web_network
    depends_on:
      - app

networks:
  web_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
