version: '3'
services:
  app:
    container_name: uploading-mast
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
      - next:/app/.next
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    restart: always
    networks:
      - web_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - web_network
    depends_on:
      - app

networks:
  web_network:
    driver: bridge

volumes:
  next:
    driver: local
  node_modules:
    driver: local
